/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Chronique
 */
export interface ChroniqueBE { 
    /**
     * Code de la station de mesure: Identifiant de la station de mesure dans le référentiel national Sandre
     */
    code_station?: string;
    /**
     * Libellé national de la station de mesure
     */
    libelle_station?: string;
    /**
     * URI de la station de mesure
     */
    uri_station?: string;
    /**
     * Longitude du point en WGS84 pour la recherche par rayon, le point doit être utilisé comme séparateur décimal, exemple : 1.937
     */
    longitude?: number;
    /**
     * Latitude du point en WGS84 pour la recherche par rayon, le point doit être utilisé comme séparateur décimal, exemple : 47.829
     */
    latitude?: number;
    /**
     * Code INSEE de la commune où est implantée la station
     */
    code_commune?: string;
    /**
     * Libellé long de la commune
     */
    libelle_commune?: string;
    /**
     * Code du du cours d\'eau
     */
    code_cours_eau?: string;
    /**
     * Libellé long du cours d\'eau
     */
    libelle_cours_eau?: string;
    /**
     * URI du cours d\'eau
     */
    uri_cours_eau?: string;
    /**
     * Code SANDRE du paramètre mesuré (ici toujours égal à 1301)
     */
    code_parametre?: string;
    /**
     * Libellé long du paramètre mesuré (ici Température de l\'Eau)
     */
    libelle_parametre?: string;
    /**
     * Date de la mesure
     */
    date_mesure_temp?: string;
    /**
     * Heure de la mesure
     */
    heure_mesure_temp?: string;
    /**
     * Résultat
     */
    resultat?: number;
    /**
     * Code de l\'unité de mesure (ici toujours égal à 27)
     */
    code_unite?: string;
    /**
     * Symbole de l\'unité de mesure (ici toujours égal à degré C)
     */
    symbole_unite?: string;
    /**
     * Code de la qualification de l’acquisition du résultat de l’analyse de température
     */
    code_qualification?: string;
    /**
     * Libellé de la qualification de l’acquisition du résultat de l’analyse de température
     */
    libelle_qualification?: string;
}

