/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Erreur
 */
export interface ErreurBE { 
    /**
     * Code de l\'erreur
     */
    code?: string;
    /**
     * Message en rapport avec l\'erreur sur le paramètre
     */
    message?: string;
    /**
     * Le nom du paramètre avec l\'erreur
     */
    field?: string;
}

