/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErreurBE } from './erreur';


/**
 * Message d\'erreur
 */
export interface Message derreurBE { 
    /**
     * Code de l\'erreur
     */
    code?: string;
    /**
     * Message en rapport avec l\'erreur
     */
    message?: string;
    /**
     * Liste des paramètres avec des erreurs
     */
    field_errors?: Array<ErreurBE>;
}

