/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CrsBE } from './crs';
import { LngLatAltBE } from './lngLatAlt';


export interface PointBE { 
    bbox?: Array<number>;
    coordinates?: LngLatAltBE;
    crs?: CrsBE;
}

