/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StationBE } from './station';


/**
 * Résultat d\'une rêquete sur les stations
 */
export interface Rsultat dune rquete sur les stationsBE { 
    /**
     * Le nombre total de résultat
     */
    count: number;
    /**
     * URL de la 1er page des résultats
     */
    first: string;
    /**
     * URL de la dernière page des résultats (non disponible quand la pagination utilise un curseur)
     */
    last: string;
    /**
     * URL de la page précédente
     */
    prev: string;
    /**
     * URL de la page suivante
     */
    next: string;
    /**
     * Version de l\'API (<a href=\'https://semver.org/\' target=\'_blank\'>https://semver.org/</a>)
     */
    api_version: string;
    /**
     * Les résultats de la requête sous forme de liste
     */
    data: Array<StationBE>;
}

