/**
 * API Hub\'Eau - Température des cours d\'eau en continu
 * Adresse de la documentation http://hubeau.eaufrance.fr/page/api-temperature-en-continu-cours-deau
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointBE } from './point';


/**
 * Station
 */
export interface StationBE { 
    /**
     * Code de la station de mesure: Identifiant de la station de mesure dans le référentiel national Sandre
     */
    code_station?: string;
    /**
     * Libellé national de la station de mesure
     */
    libelle_station?: string;
    /**
     * URI de la station de mesure
     */
    uri_station?: string;
    /**
     * Localisation précise de la station de mesure
     */
    localisation?: string;
    /**
     * Coordonnée X du point caractéristique de la station de mesure
     */
    coordonnee_x?: number;
    /**
     * Coordonnée Y du point caractéristique de la station de mesure
     */
    coordonnee_y?: number;
    /**
     * Code du type de projection des coordonnées de la station de mesure
     */
    code_type_projection?: number;
    /**
     * Longitude du point en WGS84 pour la recherche par rayon, le point doit être utilisé comme séparateur décimal, exemple : 1.937
     */
    longitude?: number;
    /**
     * Latitude du point en WGS84 pour la recherche par rayon, le point doit être utilisé comme séparateur décimal, exemple : 47.829
     */
    latitude?: number;
    /**
     * Code INSEE de la commune où est implantée la station
     */
    code_commune?: string;
    /**
     * Libellé long de la commune
     */
    libelle_commune?: string;
    /**
     * Code du département
     */
    code_departement?: string;
    /**
     * Libellé long du département
     */
    libelle_departement?: string;
    /**
     * Code de la région (INSEE)
     */
    code_region?: string;
    /**
     * Libellé long de la région
     */
    libelle_region?: string;
    /**
     * Code du tronçon hydrographique associé à la station
     */
    code_troncon_hydro?: string;
    /**
     * Code du du cours d\'eau
     */
    code_cours_eau?: string;
    /**
     * Libellé long du cours d\'eau
     */
    libelle_cours_eau?: string;
    /**
     * URI du cours d\'eau
     */
    uri_cours_eau?: string;
    /**
     * Code national de la masse d’eau de la station de mesure
     */
    code_masse_eau?: string;
    /**
     * Nom de la masse d’eau
     */
    libelle_masse_eau?: string;
    /**
     * URI de la masse d\'eau
     */
    uri_masse_eau?: string;
    /**
     * Code européen du sous-bassin DCE administratif
     */
    code_sous_bassin?: string;
    /**
     * Nom du sous bassin DCE administratif
     */
    libelle_sous_bassin?: string;
    /**
     * Code national du bassin DCE
     */
    code_bassin?: string;
    /**
     * Nom du bassin DCE
     */
    libelle_bassin?: string;
    /**
     * URI du bassin DCE (régions hydrographiques)
     */
    uri_bassin?: string;
    /**
     * Point kilométrique du point caractéristique sur le tronçon de l\'entité hydrographique principale
     */
    pk?: number;
    /**
     * Altitude du point caractéristique de la station de mesure
     */
    altitude?: number;
    /**
     * Date de mise à jour des informations sur la station de mesure
     */
    date_maj_infos?: string;
    geometry?: PointBE;
}

