/**
 * API Géo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DepartementBE } from './departement';
import { RegionBE } from './region';


export interface CommuneBE { 
    /**
     * Code INSEE de la commune
     */
    code?: string;
    /**
     * Nom de la commune
     */
    nom?: string;
    /**
     * Liste des codes postaux associés à la commune
     */
    codesPostaux?: Array<string>;
    /**
     * Code du département associé à la commune
     */
    codeDepartement?: string;
    /**
     * Code de la région associée à la commune
     */
    codeRegion?: string;
    departement?: DepartementBE;
    region?: RegionBE;
    /**
     * Population municipale
     */
    population?: number;
    /**
     * Surface de la commune, en hectares
     */
    surface?: number;
    /**
     * Centre de la commune (Point GeoJSON)
     */
    centre?: object;
    /**
     * Contour de la commune (Polygon GeoJSON)
     */
    contour?: object;
}

