/**
 * API Géo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegionBE } from './region';


export interface DepartementBE { 
    /**
     * Code du département
     */
    code?: string;
    /**
     * Nom du département
     */
    nom?: string;
    /**
     * Code de la région
     */
    codeRegion?: string;
    region?: RegionBE;
}

